<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.yexianglun-d</groupId>
        <artifactId>under-utils</artifactId>
        <version>1.0.6-SNAPSHOT</version>
    </parent>

    <artifactId>under-utils-starter</artifactId>

    <name>Under-Utils Starter</name>
    <description>兼容聚合 Starter，按需引入 Spring 与 Redis 自动配置模块</description>

    <dependencies>
        <dependency>
            <groupId>io.github.yexianglun-d</groupId>
            <artifactId>under-utils-spring-starter</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.yexianglun-d</groupId>
            <artifactId>under-utils-redis-starter</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
